const LOADING = 'LOADING';
const GET_UPLOADED_CATS = 'GET_UPLOADED_CATS';
const GET_UPLOADED_CATS_SUCCESS = 'GET_UPLOADED_CATS_SUCCESS';
const GET_UPLOADED_CATS_FAILURE = 'GET_UPLOADED_CATS_FAILURE';
const GET_FAVOURITE_CATS = 'GET_FAVOURITE_CATS';
const GET_FAVOURITE_CATS_SUCCESS = 'GET_FAVOURITE_CATS_SUCCESS';
const GET_FAVOURITE_CATS_FAILURE = 'GET_FAVOURITE_CATS_FAILURE';
export {
    LOADING,
    GET_UPLOADED_CATS,
    GET_UPLOADED_CATS_SUCCESS,
    GET_UPLOADED_CATS_FAILURE,
    GET_FAVOURITE_CATS,
    GET_FAVOURITE_CATS_SUCCESS,
    GET_FAVOURITE_CATS_FAILURE
}
